### ISSUE TITLE
ansible-lint fails when using role with embeded modules

### ISSUE THREAD

**Issue by mgagne** [willthames/ansible-lint#145]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible==2.0.1.0
ansible-lint==2.5.0
```

# Desired Behaviour

ansible-lint versions before 2.5.0 used to work fine with role with [embedded modules](http://docs.ansible.com/ansible/playbooks_roles.html#embedding-modules-in-roles).

# Actual Behaviour

ansible-lint fails when ran against a playbook using a role with embedded modules.

```
Traceback (most recent call last):
  File "/Users/mgagne/venv/ansible/bin/ansible-lint", line 125, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/mgagne/venv/ansible/bin/ansible-lint", line 112, in main
    matches = runner.run()
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansiblelint/__init__.py", line 222, in run
    skip_list=set(self.skip_list)))
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansiblelint/__init__.py", line 134, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansiblelint/__init__.py", line 62, in matchtasks
    for task in ansiblelint.utils.get_action_tasks(yaml, file):
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansiblelint/utils.py", line 368, in get_action_tasks
    if 'include' not in task.keys()]
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansiblelint/utils.py", line 326, in normalize_task
    return normalize_task_v2(task)
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansiblelint/utils.py", line 258, in normalize_task_v2
    action, arguments, result['delegate_to'] = mod_arg_parser.parse()
  File "/Users/mgagne/venv/ansible/lib/python2.7/site-packages/ansible/parsing/mod_args.py", line 304, in parse
    raise AnsibleParserError("no action detected in task. This often indicates a misspelled module name, or incorrect module path.", obj=self._task_ds)
ansible.errors.AnsibleParserError: no action detected in task. This often indicates a misspelled module name, or incorrect module path.
```

**Comment by cloudnull** [comment]
While we're currently not seeing this in the OpenStack-Ansible roles because we're capped at ``<=2.3.9`` this is something that currently effects a few of our roles because we do use embedded modules. I've not looked into the code to see what the issue is however this is forcing us to keep our constraints in place until its resolved.

Roles that we have which are effected:
  * https://github.com/openstack/openstack-ansible-os_neutron
  * https://github.com/openstack/openstack-ansible-os_keystone
  * https://github.com/openstack/openstack-ansible-galera_server

**Comment by willthames** [comment]
Thanks @mgagne for the excellent bug report and @cloudnull for the extra detail and pull request.

I'll leave this unclosed for now - I consider #146 a workaround.

I'll update this again when I have a proper fix (or give up looking for a proper fix)

**Comment by cloudnull** [comment]
Thank @willthames for the review. If there's anything we can do to help out, look into things, and or test please let us know.

**Comment by willthames** [comment]
I'm not sure this is only a problem with embedded modules. 

Looking at openstack-ansible-os_neutron, it is relying on config_template, which is not embedded in the role.

However, it's also the case that ansible-lint was ignoring looking under roles for libraries. I think I have a change for that in 42988c4 so it might be worth testing against the v2.6 branch and see if that improves matters.

**Comment by cloudnull** [comment]
@willthames i'll give that a go and report back. Thanks!

**Comment by jbruggem** [comment]
In case it's relevant: we have the same symptoms and we also have an embedded module. We can help test a patch.

**Comment by willthames** [comment]
Hi, I think I might have fixed this now. Certainly a simple playbook that just includes the openstack galera role works, once I also installed the openstack-ansible-plugins repo too.

My main concern is whether this change misses anything. 

I've pushed ansible-lint v2.7.0rc1 to pip so that this can be tested, or you can use the v2.7 source branch.

Please note that v3.0 is around the corner, so I've rebased v3.0 on this change, and 3.0.0rc6 is now available for testing too.

**Comment by willthames** [comment]
v2.7 is released.
