### ISSUE TITLE
Homebrew recipe ?

### ISSUE THREAD

**Issue by tristanbes** [willthames/ansible-lint#213]
# Issue Type
- Feature request
# Desired Behaviour

I would like to install `ansible-lint` with much simplicity using **Homebrew** because right now on a MacOSX 10.12, it doesn't come with `pip` or `pip2`. Would be awesome 🐱

**Comment by willthames** [comment]
This would indeed be nice to have if anyone is willing to take it on.

**Comment by zizzfizzix** [comment]
I have come quite close, but the way python packages are built is just too overwhelming.
I used http://docs.brew.sh/Python-for-Formula-Authors.html as a guide. The formula works but ansible-lint doesn't work due to missing ansible dependency (which in turn has a million dependencies).
If anyone is interested it's here: https://gist.github.com/zizzfizzix/b48079964a27c7e7d37dc37969607bae

**Comment by Nklya** [comment]
I've made PR with working ansible-lint formula to homebrew-core.
https://github.com/Homebrew/homebrew-core/pull/12806

**Comment by tima** [comment]
Following the above link and [this entry](https://formulae.brew.sh/formula/ansible-lint) in seems that has been happened and can be closed @willthames.

**Comment by willthames** [comment]
Thanks @Nklya for doing this!
