### ISSUE TITLE
Easily disabling some of the rules?

### ISSUE THREAD

**Issue by inadarei** [willthames/ansible-lint#54]
First: thanks for this project!

Now the question:

Is there any less surgical way to disable a rule other than removing it from `/usr/local/lib/python2.7/dist-packages/ansiblelint/rules`?

For instance, I really don't care for the trailing whitespace rule, to be honest, so it would be great if people could create a configuration file like you can with jslint or jshint.

Thanks!

**Comment by willthames** [comment]
Thanks!

At the moment there are a couple of options:
* use `-x` to skip rules with tags. But that might still not be specific enough. 
* Copy all the rules to another directory and delete the ones you don't want, and then specify the path with `-r`.

A configuration file would be a good idea - I don't really have time to implement such a feature at the moment but a working pull request would definitely be favourably considered

**Comment by charleswhchan** [comment]
I would like this feature as well. Due to some outstanding issues/bugs in the Ansible 1.9 release, it's not always possible to achieve full compliance. As you mention:

* `-x` is too broad, eg. both ANSIBLE0006 and ANSIBLE0007 belong to the resource tag.
* `-r` requires additional maintainence to keep them in sync & updated.

I agree having a configuration file would be excellent, even something like .pylintrc. As I understand this is too much work. Would it be easier to add another command line option to allow exclusion based on ANSIBLExxxx? Or, alternatively overload the `-x` option to support exclusion for tags **or** rules?

**Comment by willthames** [comment]
@charleswhchan that's a good idea. I still don't have much time available to look at it, but would support a pull request implementing such a change :)

Otherwise, I'll leave this open and see if I get bored at some point!

**Comment by charleswhchan** [comment]
@willthames Created PR 73. Please review. :relaxed:

**Comment by willthames** [comment]
Thanks @charleswhchan for #73.

We might still want a configuration file so I'll leave this open for now.

**Comment by charleswhchan** [comment]
No problem. :relaxed:

**Comment by willthames** [comment]
Closing this now - if we do want a configuration file, let's have that as a separate issue, preferably as a PR ;)

**Comment by aairey** [comment]
As with every linter, this feels like a basic requirement ...

**Comment by willthames** [comment]
@aairey and has a basic solution, using `-x` as per #73 

Either that or use [ansible-review](https://github.com/willthames/ansible-review) which is much more configurable as to what rules are used.

**Comment by aairey** [comment]
Thanks @willthames, I wasn't aware.

Reading this[0] cleared it up for me.
I will switch to ansible-review.

[0]: https://github.com/willthames/ansible-review/issues/31
