### ISSUE TITLE
No doc on how to run tests

### ISSUE THREAD

**Issue by lxsli** [willthames/ansible-lint#92]
There's no tox.ini and if I try to run nosetests, I'm missing ansible.utils. My venv has Ansible 1.9.2 in it as that's what we run with.

**Comment by willthames** [comment]
There is a tox.ini - https://github.com/willthames/ansible-lint/blob/a8f89d33ac50c30cfe125eaffffa36b68af2ae69/tox.ini

Perhaps provide a pip freeze and the output of what happens when you run tox or nosetests.

I can try and recreate on a fresh VM when I have some time, but that's not right now I'm afraid.

**Comment by lxsli** [comment]
Right, derp, I see it - I need to rebase my fork, thanks.
