### ISSUE TITLE
file module, mode check request

### ISSUE THREAD

**Issue by bhcopeland** [willthames/ansible-lint#94]
As per http://docs.ansible.com/ansible/file_module.html:

"For those used to /usr/bin/chmod remember that modes are actually octal numbers (like 0644). Leaving off the leading zero will likely have unexpected results. "

Can we get a lint check for this?

**Comment by willthames** [comment]
It sounded like @siddhardthist was offering to create a PR for this in #99. I would certainly consider such a PR very favourably, particularly one that included a test case for the various possibilities (`mode=644`, `mode=0644`, mode=`g+rwx` etc)

**Comment by siddharthist** [comment]
@willthames I am currently working on implementing this.

**Comment by siddharthist** [comment]
As it turns out, this is currently impossible with the `matchtask` method, because the `mode` is parsed and stored in the task dict as an int, which erases whether or not it had leading zeroes in the first place. Is there another way to go about this @willthames?

You can see my work so far [here](https://github.com/willthames/ansible-lint/compare/siddharthist:rule/OctalFilePermissions).
